"""
reporting/report_generator.py
------------------------------
Deterministic assembly and formatting of the LegalDocumentReport.

This module contains ZERO LLM calls. Everything here is pure Python:
looping over Pydantic objects, translating floats to labels, formatting
markdown tables, and serializing to JSON. The one LLM call (executive
summary generation) lives in reporting/executive_summary.py (Stage 3)
and is called from the orchestrator node, not from this module.

Why split generation from formatting?
    The assembly functions (build_*) are testable with simple unit tests
    because they have no external dependencies. The markdown/JSON renderers
    are testable by asserting on string content. If the executive summary LLM
    call is separately mocked, the rest of this module is fully deterministic
    and can run without any network calls.

Public API
----------
    confidence_to_label(confidence: float) -> tuple[str, str]
    build_clause_entries(...) -> list[ClauseReportEntry]
    build_risk_findings(risk_findings) -> list[RiskFindingEntry]
    build_guardrail_summary(guardrail_results) -> list[GuardrailSummaryEntry]
    assemble_report(...) -> LegalDocumentReport
    render_markdown(report: LegalDocumentReport) -> str
    render_json(report: LegalDocumentReport) -> str

Confidence label thresholds (justified below):
    >= 0.70 -> HIGH
    0.50-0.69 -> MODERATE
    < 0.50  -> LOW

Threshold justification:
    These mirror the confidence routing boundaries already locked in CLAUDE.md
    and implemented in classifier.py / extractor.py:
      > 0.70 -> auto-proceed (HIGH confidence: system is sure enough to proceed)
      0.50-0.70 -> Tree-of-Thought (MODERATE confidence: needs more reasoning)
      < 0.50 -> retry then HITL (LOW confidence: system is uncertain)
    Using the same boundaries in the report ensures that what the report calls
    "HIGH confidence" is EXACTLY the same thing the routing layer used to
    auto-proceed -- no inconsistency between pipeline behaviour and report text.

Writing quality rules (apply to every text field produced here):
    1. Confidence language must never overclaim. Always HIGH/MODERATE/LOW,
       never a percentage presented as a calibrated probability.
    2. Never state a definitive legal verdict. Use observation + recommendation
       pattern: "The system identified [X]. Qualified legal review is recommended."

Banned phrases (checked by executive_summary.py on LLM output, also manually
avoided in all templated text produced by this module):
    "is enforceable", "is unenforceable", "is valid", "is invalid",
    "legally binding", "guarantees", "certifies that"
"""

import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

from config import CLAUSE_CATEGORIES
from schemas.clause import ExtractedClause
from schemas.report import (
    ClauseReportEntry,
    GuardrailSummaryEntry,
    LegalDocumentReport,
    RiskFindingEntry,
)
from schemas.risk import RiskFinding

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Fixed text blocks (disclaimer is identical on every report)
# ---------------------------------------------------------------------------

DISCLAIMER = (
    "This report was generated by an AI-assisted legal document analysis system. "
    "It does not constitute legal advice and must not be relied upon as a substitute "
    "for qualified legal counsel. The system identifies patterns and potential areas "
    "of concern; it does not determine whether any clause, contract, or agreement is "
    "enforceable, valid, or fit for any specific purpose. All findings should be "
    "reviewed by a qualified legal professional before any binding decision is made."
)

# ---------------------------------------------------------------------------
# Confidence thresholds (mirroring CLAUDE.md routing boundaries exactly)
# ---------------------------------------------------------------------------

_HIGH_THRESHOLD = 0.70    # >= this -> HIGH (auto-proceed boundary from CLAUDE.md)
_MODERATE_FLOOR = 0.50    # >= this -> MODERATE (ToT routing band from CLAUDE.md)
# < _MODERATE_FLOOR -> LOW


def confidence_to_label(confidence: float) -> tuple[str, str]:
    """
    Translate a 0-1 confidence float to a (label, explanation) tuple.

    Returns
    -------
    label : str
        "HIGH", "MODERATE", or "LOW"
    explanation : str
        One sentence suitable for a human-facing report explaining WHY this
        label applies. Never states a calibrated probability.

    Thresholds:
        >= 0.70 -> HIGH     (same as auto-proceed in classifier/extractor)
        0.50-0.69 -> MODERATE (same as ToT routing band)
        < 0.50  -> LOW      (below retry floor; extraction was uncertain)
    """
    if confidence >= _HIGH_THRESHOLD:
        return (
            "HIGH",
            "High confidence: the system located and verified this clause with "
            "strong signal from the source document.",
        )
    elif confidence >= _MODERATE_FLOOR:
        return (
            "MODERATE",
            "Moderate confidence: the system identified this clause but the "
            "extracted text required additional reasoning to resolve ambiguity.",
        )
    else:
        return (
            "LOW",
            "Low confidence: the system was uncertain about this extraction; "
            "the result should be independently verified by a reviewer.",
        )


# ---------------------------------------------------------------------------
# Assembly helpers
# ---------------------------------------------------------------------------

def build_clause_entries(
    clauses: List[ExtractedClause],
    risk_findings: List[RiskFinding],
    evidence_results: Optional[List[Dict]] = None,
) -> List[ClauseReportEntry]:
    """
    Build one ClauseReportEntry per clause.

    Parameters
    ----------
    clauses : list[ExtractedClause]
        All extracted clauses (always 10 per document).
    risk_findings : list[RiskFinding]
        Risk findings, one per clause category.
    evidence_results : list[dict] or None
        Evidence verification result dicts from node_verify_clauses.
        Each dict has at least: clause_type, evidence_found.
        None if the evidence verifier did not run.

    Returns
    -------
    list[ClauseReportEntry]
        One entry per clause, in the order supplied.
    """
    risk_by_type: Dict[str, RiskFinding] = {f.clause_type: f for f in risk_findings}
    evidence_by_type: Dict[str, bool] = {}
    if evidence_results:
        for ev in evidence_results:
            ctype = ev.get("clause_type")
            if ctype is not None:
                evidence_by_type[ctype] = bool(ev.get("evidence_found"))

    entries = []
    for clause in clauses:
        if clause.is_present:
            label, explanation = confidence_to_label(clause.confidence)
        else:
            # Clause is absent — the extractor found no text to evaluate.
            # confidence=0.0 on an absent clause is not a low-confidence
            # extraction; it means confidence is not applicable.  Showing
            # "LOW" here would imply the system tried and was uncertain,
            # which is wrong.
            label = "N/A"
            explanation = "Clause is absent — extraction confidence is not applicable."
        finding = risk_by_type.get(clause.clause_type)
        risk_level = finding.risk_level if finding else None
        deviation = finding.deviation_summary if finding else None

        # Build deviation_summary in observation style if one exists
        deviation_entry: Optional[str] = None
        if deviation:
            deviation_entry = (
                f"The system identified a deviation from the standard template: "
                f"{deviation} Qualified legal review is recommended."
            )

        # Build recommendation
        recommendation: Optional[str] = None
        if not clause.is_present:
            recommendation = (
                f"The {clause.clause_type} clause was not found in this document. "
                "Its absence has been flagged as a potential risk. "
                "Qualified legal review is recommended to determine whether this "
                "omission is intentional or material."
            )
        elif risk_level in ("HIGH", "MEDIUM"):
            recommendation = (
                f"The system identified a {risk_level.lower()}-risk finding for "
                f"the {clause.clause_type} clause. "
                "Qualified legal review is recommended before execution."
            )

        evidence_verified = evidence_by_type.get(clause.clause_type) if clause.is_present else None

        entries.append(ClauseReportEntry(
            clause_category=clause.clause_type,
            is_present=clause.is_present,
            confidence_label=label,
            confidence_explanation=explanation,
            source_page=clause.page_reference,
            evidence_verified=evidence_verified,
            risk_level=risk_level,
            deviation_summary=deviation_entry,
            recommendation=recommendation,
        ))

    return entries


def build_risk_findings(risk_findings: List[RiskFinding]) -> List[RiskFindingEntry]:
    """
    Build one RiskFindingEntry per RiskFinding, sorted HIGH -> MEDIUM -> LOW.

    All finding_summary text follows the observation + recommendation pattern.
    Verdict-style language is never produced here.
    """
    def _sort_key(f: RiskFinding) -> int:
        return {"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(f.risk_level, 3)

    sorted_findings = sorted(risk_findings, key=_sort_key)

    entries = []
    for f in sorted_findings:
        if f.is_missing:
            summary = (
                f"The system identified that the {f.clause_type} clause is absent "
                f"from this document. Absence of this clause type is classified as "
                f"{f.risk_level} risk. Qualified legal review is recommended to "
                "assess whether this omission is material."
            )
        else:
            base = f.reason or f"The {f.clause_type} clause was assessed at {f.risk_level} risk."
            summary = (
                f"The system identified the following for the {f.clause_type} clause: "
                f"{base} Qualified legal review is recommended."
            )
            if f.precedent_applied and f.precedent_note:
                summary += f" Note: {f.precedent_note}"

        source_page: Optional[int] = None
        if f.source_clause and f.source_clause.page_reference:
            source_page = f.source_clause.page_reference

        entries.append(RiskFindingEntry(
            clause_category=f.clause_type,
            risk_level=f.risk_level,
            finding_summary=summary,
            source_page=source_page,
            precedent_applied=f.precedent_applied,
            human_review_status="not_required",
        ))

    return entries


def build_guardrail_summary(guardrail_results: List[Dict]) -> List[GuardrailSummaryEntry]:
    """
    Build one GuardrailSummaryEntry per guardrail result dict.

    PII-safe: passes through the reason field from GuardrailResult, which
    was already sanitised at guardrail time (no contract text, no injection
    patterns, no personal identifiers).
    """
    entries = []
    for gr in guardrail_results:
        entries.append(GuardrailSummaryEntry(
            guardrail_name=gr.get("guardrail_name", "unknown"),
            passed=bool(gr.get("passed", True)),
            severity=gr.get("severity", "info"),
            reason=gr.get("reason", "No details recorded."),
        ))
    return entries


def assemble_report(
    document_name: str,
    document_hash: str,
    document_type: str,
    classification_confidence: float,
    total_pages: int,
    clauses: List[ExtractedClause],
    risk_findings: List[RiskFinding],
    guardrail_results: List[Dict],
    evidence_results: Optional[List[Dict]] = None,
    human_review_decisions: Optional[List[Dict]] = None,
    executive_summary: str = "",
    processing_notes: Optional[str] = None,
) -> LegalDocumentReport:
    """
    Assemble a complete LegalDocumentReport from pipeline outputs.

    This is the main entry point called by the orchestrator's generate_report
    node. It calls all the build_* helpers and applies the fixed DISCLAIMER.

    Parameters
    ----------
    executive_summary : str
        Pre-generated executive summary text (from executive_summary.py or
        the fallback template). Passed in rather than generated here to keep
        this module free of LLM calls.
    """
    conf_label, _ = confidence_to_label(classification_confidence)

    clause_entries = build_clause_entries(clauses, risk_findings, evidence_results)
    risk_entries = build_risk_findings(risk_findings)
    guardrail_entries = build_guardrail_summary(guardrail_results)

    present = [c for c in clauses if c.is_present]
    missing_names = [c.clause_type for c in clauses if not c.is_present]

    # Limitations note: flag clause categories without template comparison data
    no_deviation_data = [
        e.clause_category for e in clause_entries
        if e.is_present and e.deviation_summary is None
    ]
    if no_deviation_data:
        limitations_note = (
            f"Template comparison data was not available for "
            f"{len(no_deviation_data)} of 10 clause categories "
            f"({', '.join(no_deviation_data[:3])}{'...' if len(no_deviation_data) > 3 else ''}). "
            "Risk assessments for those categories reflect only clause presence/absence, "
            "not deviation from a standard baseline."
        )
    else:
        limitations_note = (
            "Template comparison data was available for all 10 clause categories."
        )

    if not executive_summary:
        executive_summary = _fallback_executive_summary(
            document_type=document_type,
            total_found=len(present),
            risk_entries=risk_entries,
            missing_names=missing_names,
            clause_entries=clause_entries,
        )

    decisions = human_review_decisions or []

    return LegalDocumentReport(
        document_name=document_name,
        document_hash=document_hash,
        document_type=document_type,
        classification_confidence_label=conf_label,
        total_pages=total_pages,
        total_clauses_found=len(present),
        total_clauses_missing=len(missing_names),
        executive_summary=executive_summary,
        clause_entries=clause_entries,
        risk_findings=risk_entries,
        missing_clauses=missing_names,
        guardrail_summary=guardrail_entries,
        human_review_decisions=decisions,
        limitations_note=limitations_note,
        disclaimer=DISCLAIMER,
        generated_at=datetime.utcnow(),
        processing_notes=processing_notes,
    )


def _fallback_executive_summary(
    document_type: str,
    total_found: int,
    risk_entries: List[RiskFindingEntry],
    missing_names: List[str],
    clause_entries: Optional[List] = None,
) -> str:
    """
    Deterministic fallback summary used when the LLM call is unavailable
    or produces a rule-violating response.

    Follows both writing-quality rules: HIGH/MODERATE/LOW labels only,
    observation + recommendation pattern, no verdict language.

    Evidence verification phrasing explicitly distinguishes present-and-verified
    from absent-and-N/A so the summary cannot be read as a blanket reassurance.
    """
    high = [r for r in risk_entries if r.risk_level == "HIGH"]
    medium = [r for r in risk_entries if r.risk_level == "MEDIUM"]

    parts = [
        f"This {document_type} contains {total_found} of 10 standard clause categories."
    ]

    if missing_names:
        parts.append(
            f"The following clause categories were not found: "
            f"{', '.join(missing_names)}."
        )

    if high:
        parts.append(
            f"{len(high)} high-risk finding(s) were identified "
            f"({', '.join(r.clause_category for r in high)})."
        )
    if medium:
        parts.append(
            f"{len(medium)} medium-risk finding(s) were identified "
            f"({', '.join(r.clause_category for r in medium)})."
        )

    # Evidence verification: distinguish verified-and-passed from absent-and-N/A.
    # Never describe absent clauses as "no issues" -- they were never checked.
    if clause_entries is not None:
        ev_passed = sum(1 for e in clause_entries if e.is_present and e.evidence_verified is True)
        na_count = sum(1 for e in clause_entries if not e.is_present)
        if total_found > 0:
            parts.append(
                f"All {ev_passed} present clause(s) passed evidence verification; "
                f"the remaining {na_count} clause(s) were absent and not applicable "
                "for this check."
            )

    parts.append("Qualified legal review is recommended before execution.")
    return " ".join(parts)


# ---------------------------------------------------------------------------
# Rendering: Markdown
# ---------------------------------------------------------------------------

_REQUIRED_HEADERS = [
    "Executive Summary",
    "Document Metadata",
    "Clause Analysis",
    "High-Risk Findings",
    "Medium-Risk Findings",
    "Missing Clauses",
    "Guardrail Summary",
    "Human Review Decisions",
    "Recommendations",
    "Confidence and Limitations",
    "Disclaimer",
]


def render_markdown(report: LegalDocumentReport) -> str:
    """
    Render the LegalDocumentReport to Markdown.

    Section order follows Section 30 of the project's original system prompt:
    executive summary, document metadata, classification, clause-analysis table,
    high-risk findings, medium-risk findings, missing clauses, template deviations,
    source evidence/pages, human-review decisions, recommendations, confidence
    and limitations, processing notes, disclaimer.
    """
    lines: List[str] = []

    lines.append("# Legal Document Analysis Report")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(report.executive_summary)
    lines.append("")

    lines.append("## Document Metadata")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Document Name | {report.document_name} |")
    lines.append(f"| Document Type | {report.document_type} |")
    lines.append(f"| Classification Confidence | {report.classification_confidence_label} |")
    lines.append(f"| Total Pages | {report.total_pages} |")
    lines.append(f"| Clauses Found | {report.total_clauses_found} / 10 |")
    lines.append(f"| Clauses Missing | {report.total_clauses_missing} |")
    lines.append(f"| Document Hash | `{report.document_hash[:16]}...` |")
    lines.append(f"| Generated At | {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')} |")
    lines.append("")

    lines.append("## Clause Analysis")
    lines.append("")
    lines.append("| Clause Category | Present | Confidence | Evidence Verified | Risk Level | Page |")
    lines.append("|---|---|---|---|---|---|")
    for entry in report.clause_entries:
        present = "Yes" if entry.is_present else "**No**"
        ev = ("Yes" if entry.evidence_verified else "No") if entry.evidence_verified is not None else "N/A"
        risk = entry.risk_level or "—"
        page = str(entry.source_page) if entry.source_page else "—"
        lines.append(
            f"| {entry.clause_category} | {present} | {entry.confidence_label} "
            f"| {ev} | {risk} | {page} |"
        )
    lines.append("")

    # Compute rejected categories for exclusion from risk tables
    _rejected = {
        d.get("clause_category") for d in (report.human_review_decisions or [])
        if d.get("action") == "reject" and d.get("discarded", False)
    }

    lines.append("## High-Risk Findings")
    lines.append("")
    high = [r for r in report.risk_findings if r.risk_level == "HIGH" and r.clause_category not in _rejected]
    if high:
        for finding in high:
            lines.append(f"### {finding.clause_category}")
            lines.append("")
            lines.append(finding.finding_summary)
            if finding.source_page:
                lines.append(f"*Source page: {finding.source_page}*")
            if finding.precedent_applied:
                lines.append("*Note: A precedent override was applied to this finding.*")
            lines.append("")
    else:
        lines.append("No high-risk findings were identified.")
        lines.append("")

    lines.append("## Medium-Risk Findings")
    lines.append("")
    medium = [r for r in report.risk_findings if r.risk_level == "MEDIUM" and r.clause_category not in _rejected]
    if medium:
        for finding in medium:
            lines.append(f"### {finding.clause_category}")
            lines.append("")
            lines.append(finding.finding_summary)
            if finding.source_page:
                lines.append(f"*Source page: {finding.source_page}*")
            lines.append("")
    else:
        lines.append("No medium-risk findings were identified.")
        lines.append("")

    lines.append("## Missing Clauses")
    lines.append("")
    if report.missing_clauses:
        for name in report.missing_clauses:
            lines.append(f"- **{name}** — clause was not found in the document.")
        lines.append("")
        lines.append(
            "_Each missing clause has been flagged as a potential risk. "
            "Qualified legal review is recommended to assess whether any omission is material._"
        )
    else:
        lines.append("All 10 standard clause categories were found in this document.")
    lines.append("")

    deviations = [e for e in report.clause_entries if e.deviation_summary]
    lines.append("## Template Deviations")
    lines.append("")
    if deviations:
        for entry in deviations:
            lines.append(f"**{entry.clause_category}** (page {entry.source_page or '—'})")
            lines.append("")
            lines.append(entry.deviation_summary)
            lines.append("")
    else:
        lines.append("No material template deviations were identified.")
    lines.append("")

    lines.append("## Source Evidence and Page References")
    lines.append("")
    evidence_entries = [e for e in report.clause_entries if e.is_present]
    if evidence_entries:
        lines.append("| Clause Category | Page | Evidence Verified |")
        lines.append("|---|---|---|")
        for entry in evidence_entries:
            page = str(entry.source_page) if entry.source_page else "—"
            ev = ("Yes" if entry.evidence_verified else "No") if entry.evidence_verified is not None else "N/A"
            lines.append(f"| {entry.clause_category} | {page} | {ev} |")
    else:
        lines.append("No clauses were present to verify.")
    lines.append("")

    lines.append("## Human Review Decisions")
    lines.append("")
    lines.append(
        "_Findings are separated below by review status. Rejected findings "
        "are excluded from the risk summary tables above._"
    )
    lines.append("")

    decisions = report.human_review_decisions or []
    decided_categories = {d.get("clause_category") for d in decisions if d.get("clause_category")}
    rejected_categories = {
        d.get("clause_category") for d in decisions
        if d.get("action") == "reject" and d.get("discarded", False)
    }
    approved_categories = {d.get("clause_category") for d in decisions if d.get("action") == "approve"}
    corrected_categories = {d.get("clause_category") for d in decisions if d.get("action") == "correct"}

    # AI-only findings: present in risk_findings but not reviewed by a human
    ai_only = [
        r for r in report.risk_findings
        if r.clause_category not in decided_categories
    ]
    # Human-approved findings
    human_approved = [
        r for r in report.risk_findings
        if r.clause_category in approved_categories
    ]
    # Human-corrected findings
    human_corrected = [
        r for r in report.risk_findings
        if r.clause_category in corrected_categories
    ]

    lines.append("### AI Findings (Not Yet Reviewed)")
    lines.append("")
    if ai_only:
        for r in ai_only:
            lines.append(f"- **{r.clause_category}** [{r.risk_level}]: {r.finding_summary}")
    else:
        lines.append("All findings have been reviewed by a human.")
    lines.append("")

    lines.append("### Human-Approved Findings")
    lines.append("")
    if human_approved:
        for r in human_approved:
            d = next((x for x in decisions if x.get("clause_category") == r.clause_category and x.get("action") == "approve"), {})
            note = d.get("reviewer_note") or d.get("reason") or "—"
            lines.append(f"- **{r.clause_category}** [{r.risk_level}]: AI finding confirmed. Reviewer note: {note}")
    else:
        lines.append("No findings were explicitly approved by a human reviewer in this run.")
    lines.append("")

    lines.append("### Human-Corrected Findings")
    lines.append("")
    if human_corrected:
        for r in human_corrected:
            d = next((x for x in decisions if x.get("clause_category") == r.clause_category and x.get("action") == "correct"), {})
            corrected_risk = d.get("corrected_risk_level") or r.risk_level
            corrected_summary = d.get("corrected_summary") or "(see corrected_value in state)"
            note = d.get("reviewer_note") or d.get("reason") or "—"
            lines.append(
                f"- **{r.clause_category}**: AI risk={r.risk_level} → corrected risk={corrected_risk}. "
                f"Correction: {corrected_summary} Reviewer note: {note}"
            )
    else:
        lines.append("No findings were corrected by a human reviewer in this run.")
    lines.append("")

    lines.append("### Rejected Findings (Excluded from Risk Summary)")
    lines.append("")
    lines.append(
        "_These findings were discarded by a human reviewer and do NOT appear "
        "in the High-Risk or Medium-Risk sections above._"
    )
    lines.append("")
    rejected_decisions = [d for d in decisions if d.get("action") == "reject" and d.get("discarded", False)]
    if rejected_decisions:
        for d in rejected_decisions:
            cat = d.get("clause_category", "Unknown")
            note = d.get("reviewer_note") or d.get("reason") or "—"
            lines.append(f"- **{cat}**: Rejected. Reviewer note: {note}")
    else:
        lines.append("No findings were rejected in this run.")
    lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    has_recommendations = False
    for entry in report.clause_entries:
        if entry.recommendation:
            lines.append(f"- {entry.recommendation}")
            has_recommendations = True
    if not has_recommendations:
        lines.append("No specific recommendations were generated.")
    lines.append("")

    lines.append("## Confidence and Limitations")
    lines.append("")
    lines.append("### Confidence Labels")
    lines.append("")
    lines.append(
        "All confidence levels in this report use HIGH / MODERATE / LOW labels. "
        "These labels correspond to the system's internal routing thresholds: "
        "HIGH (>= 0.70) reflects the auto-proceed confidence boundary; "
        "MODERATE (0.50–0.69) reflects the range where additional reasoning was applied; "
        "LOW (< 0.50) reflects cases where the system was uncertain and human review "
        "is most important. These labels are NOT calibrated statistical probabilities."
    )
    lines.append("")
    lines.append("### Limitations")
    lines.append("")
    lines.append(report.limitations_note)
    lines.append("")

    if report.processing_notes:
        lines.append("## Processing Notes")
        lines.append("")
        lines.append(report.processing_notes)
        lines.append("")

    lines.append("## Guardrail Summary")
    lines.append("")
    if report.guardrail_summary:
        lines.append("| Guardrail | Passed | Severity | Notes |")
        lines.append("|---|---|---|---|")
        for g in report.guardrail_summary:
            status = "Yes" if g.passed else "No"
            lines.append(f"| {g.guardrail_name} | {status} | {g.severity} | {g.reason} |")
    else:
        lines.append("No guardrail data recorded.")
    lines.append("")

    lines.append("## Disclaimer")
    lines.append("")
    lines.append(f"_{report.disclaimer}_")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rendering: JSON
# ---------------------------------------------------------------------------

def render_json(report: LegalDocumentReport) -> str:
    """
    Serialize the LegalDocumentReport to a JSON string.

    Uses Pydantic's model_dump(mode='json') for correct datetime serialisation.
    Indented at 2 spaces for readability.
    """
    return json.dumps(report.model_dump(mode="json"), indent=2, ensure_ascii=False)
