"""
tests/unit/test_executive_summary.py
--------------------------------------
Unit tests for reporting/executive_summary.py.

The LLM call is mocked in all tests so no real API calls are made.
Tests use the same mocking pattern established in the existing
unit test suite (patch at the module import boundary).

What is tested:
    1. Successful LLM call returns the generated text.
    2. API error (any Exception) triggers fallback -- never raises.
    3. A response containing a banned verdict phrase is caught, one retry
       is attempted, and if retry also fails the check, fallback is returned.
    4. The fallback summary is itself rule-compliant (no banned phrases,
       no percentage probabilities, ends with a review recommendation).
    5. The post-generation checker (_check_output) correctly identifies
       each banned phrase and accepts clean text.
"""

import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from reporting.executive_summary import (
    AMBIGUOUS_EVIDENCE_PATTERNS,
    BANNED_PHRASES,
    _check_output,
    check_evidence_coverage_phrasing,
    generate_executive_summary,
)
from schemas.report import (
    ClauseReportEntry,
    GuardrailSummaryEntry,
    LegalDocumentReport,
    RiskFindingEntry,
)


# ---------------------------------------------------------------------------
# Test fixture: a minimal but complete LegalDocumentReport
# ---------------------------------------------------------------------------

def _make_report(with_missing: bool = False, with_high_risk: bool = False) -> LegalDocumentReport:
    from config import CLAUSE_CATEGORIES
    from datetime import datetime

    clause_entries = []
    risk_findings = []
    missing_clauses = []

    for cat in CLAUSE_CATEGORIES:
        is_present = not (with_missing and cat == "Indemnification")
        risk_level = "HIGH" if (with_high_risk and cat == "Indemnification") else "LOW"

        clause_entries.append(ClauseReportEntry(
            clause_category=cat,
            is_present=is_present,
            confidence_label="HIGH",
            confidence_explanation="High confidence: clause verified in source.",
            risk_level=risk_level if is_present else "HIGH",
        ))
        risk_findings.append(RiskFindingEntry(
            clause_category=cat,
            risk_level=risk_level,
            finding_summary=(
                f"The system identified the {cat} clause. "
                "Qualified legal review is recommended."
            ),
            human_review_status="not_required",
        ))
        if not is_present:
            missing_clauses.append(cat)

    return LegalDocumentReport(
        document_name="NDA_test.pdf",
        document_hash="cafebabe1234",
        document_type="NDA",
        classification_confidence_label="HIGH",
        total_pages=5,
        total_clauses_found=len([c for c in clause_entries if c.is_present]),
        total_clauses_missing=len(missing_clauses),
        executive_summary="Placeholder -- will be replaced by generate_executive_summary.",
        clause_entries=clause_entries,
        risk_findings=risk_findings,
        missing_clauses=missing_clauses,
        guardrail_summary=[GuardrailSummaryEntry(
            guardrail_name="input_validator.all_checks",
            passed=True,
            severity="info",
            reason="All checks passed.",
        )],
        limitations_note="Template comparison data was not available for all clauses.",
        disclaimer=(
            "This report was generated by an AI-assisted analysis system. "
            "It does not constitute legal advice."
        ),
        generated_at=datetime(2026, 6, 26, 12, 0, 0),
    )


# ---------------------------------------------------------------------------
# _check_output tests
# ---------------------------------------------------------------------------

class TestCheckOutput:
    def test_clean_text_passes(self):
        clean = (
            "This NDA contains 10 of 10 standard clauses. "
            "The system identified no high-risk findings. "
            "Qualified legal review is recommended before execution."
        )
        assert _check_output(clean) is True

    def test_each_banned_phrase_fails(self):
        for phrase in BANNED_PHRASES:
            text = f"The contract {phrase} under applicable law."
            assert _check_output(text) is False, (
                f"Expected _check_output to return False for phrase: '{phrase}'"
            )

    def test_case_insensitive(self):
        assert _check_output("This agreement IS ENFORCEABLE.") is False
        assert _check_output("This agreement IS VALID.") is False

    def test_empty_string_passes(self):
        # Empty string has no banned phrases
        assert _check_output("") is True


# ---------------------------------------------------------------------------
# generate_executive_summary: normal success
# ---------------------------------------------------------------------------

class TestGenerateExecutiveSummary:
    def _clean_response(self) -> str:
        return (
            "This NDA contains all 10 standard clause categories. "
            "The system identified no high-risk or medium-risk findings. "
            "All guardrail checks passed without issue. "
            "Qualified legal review is recommended before execution."
        )

    def test_normal_success_returns_llm_text(self):
        report = _make_report()
        mock_response = MagicMock()
        mock_response.choices[0].message.content = self._clean_response()

        with patch("reporting.executive_summary._call_llm", return_value=self._clean_response()):
            result = generate_executive_summary(report)

        assert result == self._clean_response()
        assert "qualified legal review" in result.lower()

    def test_result_is_never_empty(self):
        report = _make_report()
        with patch("reporting.executive_summary._call_llm", return_value=self._clean_response()):
            result = generate_executive_summary(report)
        assert len(result) > 10


# ---------------------------------------------------------------------------
# generate_executive_summary: API failure falls back to template
# ---------------------------------------------------------------------------

class TestApiFailureFallback:
    def test_api_error_returns_fallback(self):
        report = _make_report(with_missing=True, with_high_risk=True)

        with patch("reporting.executive_summary._call_llm", side_effect=Exception("API timeout")):
            result = generate_executive_summary(report)

        # Must not raise; must return a non-empty string
        assert isinstance(result, str)
        assert len(result) > 10

    def test_fallback_mentions_document_type(self):
        report = _make_report()
        with patch("reporting.executive_summary._call_llm", side_effect=Exception("Network error")):
            result = generate_executive_summary(report)
        assert "NDA" in result

    def test_fallback_contains_no_banned_phrases(self):
        report = _make_report(with_missing=True, with_high_risk=True)
        with patch("reporting.executive_summary._call_llm", side_effect=Exception("fail")):
            result = generate_executive_summary(report)
        lower = result.lower()
        for phrase in BANNED_PHRASES:
            assert phrase.lower() not in lower, (
                f"Fallback summary contains banned phrase: '{phrase}'"
            )

    def test_fallback_recommends_legal_review(self):
        report = _make_report()
        with patch("reporting.executive_summary._call_llm", side_effect=Exception("fail")):
            result = generate_executive_summary(report)
        assert "qualified legal review" in result.lower()


# ---------------------------------------------------------------------------
# generate_executive_summary: banned phrase triggers retry then fallback
# ---------------------------------------------------------------------------

class TestBannedPhraseRetryFallback:
    VERDICT_RESPONSE = (
        "This contract is legally binding and all clauses are valid under "
        "applicable law. The system found no issues."
    )
    # CLEAN_RESPONSE must now satisfy BOTH validators:
    #   (1) no banned verdict phrases
    #   (2) evidence-coverage check: _make_report(with_missing=True) has 9 present
    #       + 1 absent, so the response must explicitly distinguish them.
    CLEAN_RESPONSE = (
        "This NDA contains 9 of 10 standard clause categories. "
        "All 9 present clauses passed evidence verification; "
        "the remaining 1 clause (Indemnification) was absent and not applicable "
        "for this check. "
        "The system identified one high-risk finding (Indemnification). "
        "Qualified legal review is recommended before execution."
    )

    def test_first_attempt_verdict_second_clean_returns_clean(self):
        """First LLM response has banned phrase; second is clean -> use second."""
        report = _make_report(with_missing=True)
        responses = iter([self.VERDICT_RESPONSE, self.CLEAN_RESPONSE])

        with patch("reporting.executive_summary._call_llm", side_effect=responses):
            result = generate_executive_summary(report)

        assert result == self.CLEAN_RESPONSE

    def test_both_attempts_verdict_returns_fallback(self):
        """Both LLM responses have banned phrases -> return deterministic fallback."""
        report = _make_report(with_missing=True, with_high_risk=True)

        with patch(
            "reporting.executive_summary._call_llm",
            return_value=self.VERDICT_RESPONSE,
        ):
            result = generate_executive_summary(report)

        # Result should be the fallback (which has no banned phrases)
        lower = result.lower()
        for phrase in BANNED_PHRASES:
            assert phrase.lower() not in lower, (
                f"Fallback after double-failure contains banned phrase: '{phrase}'"
            )
        assert isinstance(result, str)
        assert len(result) > 10

    def test_banned_phrase_never_silently_published(self):
        """The banned phrase from the mock response must NOT appear in the result."""
        report = _make_report()
        with patch(
            "reporting.executive_summary._call_llm",
            return_value=self.VERDICT_RESPONSE,
        ):
            result = generate_executive_summary(report)

        assert "legally binding" not in result.lower(), (
            "Banned phrase 'legally binding' was silently published in the result"
        )
        assert "is valid" not in result.lower(), (
            "Banned phrase 'is valid' was silently published in the result"
        )


# ---------------------------------------------------------------------------
# Evidence verification phrasing: absent ≠ verified-clean
# ---------------------------------------------------------------------------

class TestEvidenceVerificationPhrasing:
    """
    Validates that both the fallback template and the LLM path correctly
    distinguish present-and-verified clauses from absent-and-N/A clauses.

    The specific anti-pattern being guarded: when 6 of 10 clauses are absent
    and 4 are present (all verified), the summary must NOT read as though all
    10 were verified clean.  It must state explicitly that N clauses passed
    verification and M were absent/not-applicable.
    """

    def _make_mixed_report(self) -> LegalDocumentReport:
        """4 present (all evidence_verified=True) + 6 absent — mirrors the real NDA run."""
        from config import CLAUSE_CATEGORIES
        from datetime import datetime

        present_cats = CLAUSE_CATEGORIES[:4]   # first 4 present
        absent_cats  = CLAUSE_CATEGORIES[4:]   # last 6 absent

        clause_entries = []
        risk_findings  = []
        missing_clauses = []

        for cat in present_cats:
            clause_entries.append(ClauseReportEntry(
                clause_category=cat,
                is_present=True,
                confidence_label="HIGH",
                confidence_explanation="Clause found.",
                evidence_verified=True,
                risk_level="LOW",
            ))
            risk_findings.append(RiskFindingEntry(
                clause_category=cat,
                risk_level="LOW",
                finding_summary=f"The system identified the {cat} clause.",
                human_review_status="not_required",
            ))

        for cat in absent_cats:
            clause_entries.append(ClauseReportEntry(
                clause_category=cat,
                is_present=False,
                confidence_label="LOW",
                confidence_explanation="Clause not found.",
                evidence_verified=None,
                risk_level="HIGH",
            ))
            risk_findings.append(RiskFindingEntry(
                clause_category=cat,
                risk_level="HIGH",
                finding_summary=f"The system identified that the {cat} clause is absent.",
                human_review_status="not_required",
            ))
            missing_clauses.append(cat)

        return LegalDocumentReport(
            document_name="NDA_mixed.pdf",
            document_hash="deadbeef1234",
            document_type="NDA",
            classification_confidence_label="HIGH",
            total_pages=4,
            total_clauses_found=len(present_cats),
            total_clauses_missing=len(absent_cats),
            executive_summary="Placeholder.",
            clause_entries=clause_entries,
            risk_findings=risk_findings,
            missing_clauses=missing_clauses,
            guardrail_summary=[GuardrailSummaryEntry(
                guardrail_name="input_validator.all_checks",
                passed=True,
                severity="info",
                reason="All checks passed.",
            )],
            limitations_note="",
            disclaimer="This report was generated by an AI-assisted analysis system.",
            generated_at=datetime(2026, 6, 26, 12, 0, 0),
        )

    # --- Fallback template tests (fully deterministic, no LLM mock needed) ---

    def test_fallback_does_not_say_no_evidence_issues_when_na_exists(self):
        """
        When absent clauses exist, the fallback must NOT produce the misleading
        phrase 'no evidence verification issues' (which implies absent clauses
        were checked and found clean).
        """
        from reporting.report_generator import _fallback_executive_summary

        report = self._make_mixed_report()
        result = _fallback_executive_summary(
            document_type=report.document_type,
            total_found=report.total_clauses_found,
            risk_entries=list(report.risk_findings),
            missing_names=list(report.missing_clauses),
            clause_entries=list(report.clause_entries),
        )
        lower = result.lower()
        assert "no evidence verification issues" not in lower, (
            "Fallback summary used misleading 'no evidence verification issues' "
            "phrasing when 6 absent clauses were N/A for verification."
        )

    def test_fallback_states_present_clauses_passed_explicitly(self):
        """Fallback must say how many present clauses passed evidence verification."""
        from reporting.report_generator import _fallback_executive_summary

        report = self._make_mixed_report()
        result = _fallback_executive_summary(
            document_type=report.document_type,
            total_found=report.total_clauses_found,
            risk_entries=list(report.risk_findings),
            missing_names=list(report.missing_clauses),
            clause_entries=list(report.clause_entries),
        )
        # The fallback should say "4 present clause(s) passed evidence verification"
        assert "4 present" in result and "passed evidence verification" in result, (
            f"Fallback should explicitly state 4 present clauses passed verification. Got:\n{result}"
        )

    def test_fallback_states_absent_clauses_not_applicable(self):
        """Fallback must say absent clauses were not applicable for verification."""
        from reporting.report_generator import _fallback_executive_summary

        report = self._make_mixed_report()
        result = _fallback_executive_summary(
            document_type=report.document_type,
            total_found=report.total_clauses_found,
            risk_entries=list(report.risk_findings),
            missing_names=list(report.missing_clauses),
            clause_entries=list(report.clause_entries),
        )
        lower = result.lower()
        assert "not applicable" in lower, (
            f"Fallback should state absent clauses were not applicable. Got:\n{result}"
        )

    def test_fallback_na_count_is_correct(self):
        """The N/A count in the fallback must match the number of absent clauses."""
        from reporting.report_generator import _fallback_executive_summary

        report = self._make_mixed_report()
        result = _fallback_executive_summary(
            document_type=report.document_type,
            total_found=report.total_clauses_found,
            risk_entries=list(report.risk_findings),
            missing_names=list(report.missing_clauses),
            clause_entries=list(report.clause_entries),
        )
        # 6 absent clauses -> "6 clause(s) were absent"
        assert "6" in result, (
            f"Fallback should mention 6 (the absent count). Got:\n{result}"
        )

    # --- LLM path: mock a clean response using the correct phrasing pattern ---

    def test_llm_correct_phrasing_is_accepted(self):
        """
        A response that correctly distinguishes verified-from-N/A should pass
        _check_output and be returned unchanged.
        """
        correct_response = (
            "The NDA contains 4 of 10 standard clause categories. "
            "All 4 present clauses passed evidence verification; "
            "the remaining 6 clauses were absent and not applicable for this check. "
            "The system identified 6 high-risk findings for absent clause categories. "
            "Qualified legal review is recommended before execution."
        )
        report = self._make_mixed_report()
        with patch("reporting.executive_summary._call_llm", return_value=correct_response):
            result = generate_executive_summary(report)
        assert result == correct_response

    def test_llm_ambiguous_phrasing_triggers_retry_or_fallback(self):
        """
        A response that uses the ambiguous 'no evidence verification issues detected'
        phrasing is NOT caught by _check_output (it's not a banned verdict phrase),
        but after our prompt change the LLM should no longer produce it. This test
        documents the expected fallback behavior if both LLM attempts fail a separate
        check, and confirms the fallback uses correct phrasing instead.
        """
        # Simulate both LLM attempts failing (API error) -> fallback used
        report = self._make_mixed_report()
        with patch("reporting.executive_summary._call_llm", side_effect=Exception("fail")):
            result = generate_executive_summary(report)
        # The fallback (not the misleading LLM response) should be returned
        assert "not applicable" in result.lower(), (
            "When LLM fails, fallback must use correct N/A phrasing."
        )


# ---------------------------------------------------------------------------
# Validator 2: check_evidence_coverage_phrasing — unit tests
# ---------------------------------------------------------------------------

# Correct phrasing that should pass the validator in any scenario
_CORRECT_PHRASING = (
    "The NDA contains 4 of 10 standard clause categories. "
    "All 4 present clauses passed evidence verification; "
    "the remaining 6 clauses were absent and not applicable for this check. "
    "The system identified 6 high-risk findings. "
    "Qualified legal review is recommended."
)

# Deliberately "bad-sounding" blanket phrasing — only acceptable when na_count == 0
_BLANKET_BAD_PHRASING = (
    "The NDA contains 10 of 10 standard clause categories. "
    "No evidence verification issues were detected. "
    "All checks passed. "
    "Qualified legal review is recommended."
)


class TestCheckEvidenceCoveragePhrasing:
    """
    Unit tests for check_evidence_coverage_phrasing().

    Mirrors the structure of TestCheckOutput for the verdict-phrase scanner.
    """

    # --- na_count == 0: unconditional pass ---

    def test_na_zero_any_phrasing_passes(self):
        """When na_count == 0, even blanket phrasing is acceptable (nothing is absent)."""
        assert check_evidence_coverage_phrasing(_BLANKET_BAD_PHRASING,
                                                verified_count=10, na_count=0) is True

    def test_na_zero_verified_count_irrelevant(self):
        """verified_count value is ignored when na_count == 0."""
        assert check_evidence_coverage_phrasing("Anything.", verified_count=0, na_count=0) is True

    # --- na_count > 0: ambiguous phrases must be caught ---

    @pytest.mark.parametrize("label,text", [
        ("all_clauses_verified",
         "The NDA analysis found that all clauses were verified against the source."),
        ("no_evidence_issues_blanket",
         "No evidence verification issues were detected in this document."),
        ("no_evidence_issues_blanket_found",
         "No evidence concerns were found."),
        ("no_evidence_concerns_blanket",
         "There were no significant evidence concerns identified."),
        ("evidence_verification_blanket_completion",
         "Evidence verification was completed successfully for the document."),
        ("all_evidence_checks_passed",
         "All evidence checks passed for this agreement."),
        ("everything_verified",
         "Everything was verified against the PDF source text."),
        ("evidence_check_complete",
         "The evidence check was complete and thorough."),
    ])
    def test_ambiguous_phrase_rejected_when_na_exists(self, label, text):
        """Each ambiguous pattern is rejected when na_count > 0."""
        result = check_evidence_coverage_phrasing(text, verified_count=4, na_count=6)
        assert result is False, (
            f"Pattern '{label}' should be rejected when na_count=6. "
            f"Text: {text!r}"
        )

    def test_ambiguous_phrase_case_insensitive(self):
        """Ambiguous phrase detection is case-insensitive."""
        upper = "NO EVIDENCE VERIFICATION ISSUES WERE DETECTED."
        assert check_evidence_coverage_phrasing(upper, verified_count=4, na_count=6) is False

    # --- na_count > 0: missing distinction signals must be caught ---

    def test_missing_absent_signal_rejected(self):
        """
        Summary that mentions present-clause verification but never mentions
        absent clauses being N/A should be rejected.
        """
        only_present = (
            "The system analyzed the NDA. "
            "All 4 present clauses passed evidence verification. "
            "High-risk findings were identified. "
            "Qualified legal review is recommended."
        )
        assert check_evidence_coverage_phrasing(only_present, verified_count=4, na_count=6) is False

    def test_missing_present_signal_rejected(self):
        """
        Summary that mentions absent clauses being N/A but never mentions
        present-clause verification should be rejected.
        """
        only_absent = (
            "The NDA is missing 6 of 10 standard clauses, which are not applicable. "
            "High-risk findings were identified. "
            "Qualified legal review is recommended."
        )
        assert check_evidence_coverage_phrasing(only_absent, verified_count=4, na_count=6) is False

    def test_no_signals_at_all_rejected(self):
        """Summary that mentions neither population should be rejected when na_count > 0."""
        no_signals = (
            "This NDA has 4 of 10 clause categories present. "
            "Several high-risk findings were identified. "
            "Qualified legal review is recommended."
        )
        assert check_evidence_coverage_phrasing(no_signals, verified_count=4, na_count=6) is False

    # --- na_count > 0: correct phrasing passes ---

    def test_correct_phrasing_passes(self):
        """The phrasing pattern confirmed in the real LLM run must pass."""
        assert check_evidence_coverage_phrasing(
            _CORRECT_PHRASING, verified_count=4, na_count=6
        ) is True

    def test_correct_phrasing_real_llm_text(self):
        """The actual text produced by the real LLM run (previous task) must pass."""
        real_llm_text = (
            "The analysis of the Non-Disclosure Agreement (NDA) revealed that "
            "4 out of 10 standard clause categories were present. "
            "High-risk findings were identified in the areas of Confidentiality / "
            "Non-Disclosure, Termination for Convenience, Termination for Cause, "
            "Governing Law / Jurisdiction, Indemnification, Limitation of Liability, "
            "Non-Compete / Non-Solicitation, and Assignment. "
            "All 4 present clauses passed evidence verification, while 6 absent "
            "clauses were not applicable for verification. "
            "Given the high-risk findings and the missing clauses, it is recommended "
            "that a qualified legal professional review the document."
        )
        assert check_evidence_coverage_phrasing(
            real_llm_text, verified_count=4, na_count=6
        ) is True

    def test_all_present_no_absent_with_correct_text(self):
        """When all 10 clauses are present (na_count=0), validator passes unconditionally."""
        full_coverage_text = (
            "This NDA contains all 10 standard clause categories. "
            "All clauses were verified and no evidence issues were detected. "
            "Qualified legal review is recommended."
        )
        # Even though this text has "no evidence issues were detected"
        # (which would be flagged if na_count > 0), na_count=0 means there's
        # nothing absent to mis-describe, so this passes.
        assert check_evidence_coverage_phrasing(
            full_coverage_text, verified_count=10, na_count=0
        ) is True


# ---------------------------------------------------------------------------
# End-to-end: ambiguous LLM response triggers retry then fallback
# ---------------------------------------------------------------------------

class TestEvidenceCoverageEndToEnd:
    """
    Mirrors TestBannedPhraseRetryFallback for the new evidence-coverage check.
    The ambiguous blanket phrase is NOT a verdict phrase, so _check_output alone
    would pass it -- this validates that the second validator gates it correctly.
    """

    AMBIGUOUS_RESPONSE = (
        "The NDA analysis found that 4 of 10 standard clause categories were present. "
        "No evidence verification issues were detected. "
        "The system identified 6 high-risk findings for missing clauses. "
        "Qualified legal review is recommended before execution."
    )

    CORRECT_RESPONSE = _CORRECT_PHRASING

    def _make_mixed_report(self):
        """4 present + 6 absent report -- reuse the fixture pattern."""
        from config import CLAUSE_CATEGORIES
        from datetime import datetime

        present_cats = CLAUSE_CATEGORIES[:4]
        absent_cats  = CLAUSE_CATEGORIES[4:]

        clause_entries, risk_findings, missing_clauses = [], [], []
        for cat in present_cats:
            clause_entries.append(ClauseReportEntry(
                clause_category=cat, is_present=True, confidence_label="HIGH",
                confidence_explanation="Found.", evidence_verified=True, risk_level="LOW",
            ))
            risk_findings.append(RiskFindingEntry(
                clause_category=cat, risk_level="LOW",
                finding_summary=f"The system identified the {cat} clause.",
                human_review_status="not_required",
            ))
        for cat in absent_cats:
            clause_entries.append(ClauseReportEntry(
                clause_category=cat, is_present=False, confidence_label="LOW",
                confidence_explanation="Not found.", evidence_verified=None, risk_level="HIGH",
            ))
            risk_findings.append(RiskFindingEntry(
                clause_category=cat, risk_level="HIGH",
                finding_summary=f"The system identified that the {cat} clause is absent.",
                human_review_status="not_required",
            ))
            missing_clauses.append(cat)

        return LegalDocumentReport(
            document_name="NDA_e2e_test.pdf", document_hash="aabbccdd",
            document_type="NDA", classification_confidence_label="HIGH",
            total_pages=4, total_clauses_found=len(present_cats),
            total_clauses_missing=len(absent_cats), executive_summary="Placeholder.",
            clause_entries=clause_entries, risk_findings=risk_findings,
            missing_clauses=missing_clauses,
            guardrail_summary=[GuardrailSummaryEntry(
                guardrail_name="input_validator.all_checks", passed=True,
                severity="info", reason="All checks passed.",
            )],
            limitations_note="", disclaimer="AI-generated. Not legal advice.",
            generated_at=datetime(2026, 6, 26, 12, 0, 0),
        )

    def test_ambiguous_first_correct_second_returns_correct(self):
        """
        First LLM response is ambiguous (fails evidence-coverage check);
        second is correct -> the correct response is returned.
        """
        report = self._make_mixed_report()
        responses = iter([self.AMBIGUOUS_RESPONSE, self.CORRECT_RESPONSE])
        with patch("reporting.executive_summary._call_llm", side_effect=responses):
            result = generate_executive_summary(report)
        assert result == self.CORRECT_RESPONSE

    def test_both_ambiguous_returns_fallback(self):
        """
        Both LLM responses are ambiguous -> deterministic fallback is returned.
        Fallback must contain correct N/A phrasing (validated by previous task's tests).
        """
        report = self._make_mixed_report()
        with patch("reporting.executive_summary._call_llm",
                   return_value=self.AMBIGUOUS_RESPONSE):
            result = generate_executive_summary(report)
        # Fallback must not contain the ambiguous phrase
        assert "no evidence verification issues" not in result.lower(), (
            "Fallback after double-failure must not re-introduce the ambiguous phrase."
        )
        # Fallback must contain the correct N/A phrasing
        assert "not applicable" in result.lower(), (
            "Fallback must explicitly state absent clauses were not applicable."
        )

    def test_ambiguous_phrase_is_not_verdict_phrase(self):
        """
        Confirm the ambiguous evidence response passes _check_output (verdict scanner)
        but fails check_evidence_coverage_phrasing -- demonstrating that both validators
        are independently necessary.
        """
        assert _check_output(self.AMBIGUOUS_RESPONSE) is True, (
            "The ambiguous evidence phrase should NOT be caught by the verdict-phrase scanner."
        )
        assert check_evidence_coverage_phrasing(
            self.AMBIGUOUS_RESPONSE, verified_count=4, na_count=6
        ) is False, (
            "The ambiguous evidence phrase SHOULD be caught by the evidence-coverage scanner."
        )

    def test_ambiguous_phrase_never_published_to_caller(self):
        """
        The ambiguous phrase from the mocked LLM must not appear in the
        final returned string, regardless of retry/fallback path taken.
        """
        report = self._make_mixed_report()
        with patch("reporting.executive_summary._call_llm",
                   return_value=self.AMBIGUOUS_RESPONSE):
            result = generate_executive_summary(report)
        assert "no evidence verification issues" not in result.lower(), (
            "Ambiguous evidence phrasing was silently published to the caller."
        )
